[package]
name = "db_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
md5 = "0.7.0"
uuid = {version = "1.8.0", features = ["v4"]}
openssl = "0.10.64"
postgres = "0.19.7"
postgres-openssl = "0.5.0"
mongodb = {version = "2.8.2", features = ["tokio-sync"]}
